export const ROLE_DASHBOARD = {
  juez: 'DashboardJuez',
  notario: 'DashboardNotario',
  abogado: 'DashboardAbogado',
  parte: 'DashboardParte',
  testigo: 'DashboardTestigo',
};

export const ROLE_PERMISSIONS = {
  juez: {
    verTodosExpedientes: true,
    puedeCargarDocumentos: true,
    puedeAprobarRechazar: true,
    puedeFirmar: true,
    puedeSolicitarFirma: true,
    puedeAdministrarExpedientes: true,
    puedeAdministrarParticipantes: true,
    puedeAdministrarUsuarios: false,
    soloDocumentosAutorizados: false,
    soloSolicitudesFirma: false,
    tabs: ['inicio', 'documentos', 'firma', 'avisos'],
  },
  notario: {
    verTodosExpedientes: false,
    puedeCargarDocumentos: false,
    puedeAprobarRechazar: false,
    puedeFirmar: true,
    puedeSolicitarFirma: true,
    puedeAdministrarExpedientes: false,
    puedeAdministrarParticipantes: false,
    puedeAdministrarUsuarios: false,
    soloDocumentosAutorizados: false,
    soloSolicitudesFirma: true,
    tabs: ['inicio', 'firma', 'avisos'],
  },
  abogado: {
    verTodosExpedientes: false,
    puedeCargarDocumentos: true,
    puedeAprobarRechazar: false,
    puedeFirmar: true,
    puedeSolicitarFirma: true,
    puedeAdministrarExpedientes: false,
    puedeAdministrarParticipantes: false,
    puedeAdministrarUsuarios: false,
    soloDocumentosAutorizados: false,
    soloSolicitudesFirma: false,
    tabs: ['inicio', 'documentos', 'firma', 'avisos'],
  },
  parte: {
    verTodosExpedientes: false,
    puedeCargarDocumentos: true,
    puedeAprobarRechazar: false,
    puedeFirmar: true,
    puedeSolicitarFirma: false,
    puedeAdministrarExpedientes: false,
    puedeAdministrarParticipantes: false,
    puedeAdministrarUsuarios: false,
    soloDocumentosAutorizados: true,
    soloSolicitudesFirma: false,
    tabs: ['inicio', 'documentos', 'firma', 'avisos'],
  },
  testigo: {
    verTodosExpedientes: false,
    puedeCargarDocumentos: false,
    puedeAprobarRechazar: false,
    puedeFirmar: true,
    puedeSolicitarFirma: false,
    puedeAdministrarExpedientes: false,
    puedeAdministrarParticipantes: false,
    puedeAdministrarUsuarios: false,
    soloDocumentosAutorizados: false,
    soloSolicitudesFirma: true,
    tabs: ['inicio', 'firma', 'avisos'],
  },
};

